name: video_player_for_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.0
  video_player_platform_interface: 
    git:
      url: https://github.com/BlackLeg15/plugins.git
      path: packages/video_player/video_player_platform_interface
      ref: ef3133a537a798d1bfa1ea4a3970238dbab0f202
  video_player_web:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
