name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
version: 2.1.0+5
publish_to: none
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.3.0
  video_player_platform_interface:
    git:
      url: https://github.com/fanhero/plugins.git
      ref: fanhero
      path: packages/video_player/video_player_platform_interface

  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
  pigeon: ^0.1.23

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'
